backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img
site_url: https://code-with-friends.netlify.app
display_url: https://code-with-friends.netlify.app
logo_url: https://code-with-friends.netlify.app/badge.png

collections:
  - label: 'News Item'
    name: 'news'
    preview_path: 'news/{{slug}}'
    folder: 'content/news'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image', hint: 'Used for the meta tag image and the masthead at the top. Defaults to global image if not set.' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - label: 'Static Page'
    name: 'static-page'
    preview_path: '{{slug}}'
    description: 'Pages with text content that can be added to the header or footer menu.'
    folder: 'content/static-page'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image', hint: 'Used for the meta tag image and the masthead at the top. Defaults to global image if not set.' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Default Content"
        name: "default-content"
        file: "content/settings/default-content.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
      - label: "Menus"
        name: "menus"
        file: "content/settings/menus.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
      - label: "Social Media Links"
        name: "social-media"
        file: "content/settings/social-media.md"
        fields:
          - label: 'Social Media Items'
            name: 'social-media-items'
            hint: 'These social media items will display in the Community dropdown of the header menu'
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Icon, name: icon, widget: string, hint: 'Such as `mdi-twitter`. For all available icons, visit https://materialdesignicons.com/' }
              - { label: URL, name: url, widget: string }
